Mi ldmadmin showsettings
Unidata/LDM pull request #93
Opened 2021-04-20 19:18 UTC by mustbei

2021-04-20 21:18 UTC, semmerson requested changes
"echo -e" -> printf "%s"
Remove "#!/bin/bash
Remove "bash" from invocation in ldmadmin(1)

2021-04-21 17:02 UTC, mustbei commented
Done.
Also, 
echo -e "Hi"  -> printf "\n%s" "Hi"
(i.e. newline '\n' should be inserted in the format string, not in the text string "\nHi". This only displays it literally.)

2021-04-21 17:14 UTC, semmerson approved these changes

2021-04-21 17:15 UTC, merged

2021-04-21 17:18 UTC, semmerson commented
Mustapha,

echo -e "Hi" -> printf "\n%s" "Hi"
> (i.e. newline '\n' should be inserted in the format string, not in the
> text string "\nHi". This only displays it literally.)
>

I did not know that.

Good work.

--Steve